Repository boostcamp-2020/IssueTracker-23, pull requests merged in 2020-11, with the labels that each got.

#34 [J179] dotenv, crossenv 를 적용하여 설정 변경
  server/.eslintrc.js
  server/db/config/config.js
  server/db/config/config.json
  server/db/models/index.js
  server/package-lock.json
  server/package.json
Labels: backend

#40 [J054] CommentModel.create() 메소드 Test
  server/.eslintrc.js
  server/db/migrations/20201102055312-create-comment.js
  server/db/models/comment.js
  server/db/models/issue.js
  server/db/models/label.js
  server/db/models/milestone.js
  server/db/models/repository.js
  server/db/models/user.js
  server/package-lock.json
  server/package.json
  server/test/models.comment.test.js
Labels: backend

#39 [J179] issue model 추가
  server/models/comment.js
  server/models/issue.js
Labels: backend

#38 [J003] milestone model 추가
  server/models/milestone.js
  server/util/date.js
Labels: backend

#45 [J054] LabelService 구현
  server/db/models/assignee.js
  server/db/models/issue-label.js
  server/models/label.js
  server/services/.gitkeep
  server/services/label.js
Labels: backend

#46 [J003] stauts 응답 코드, app.js에 api router, index 추가
  server/app.js
  server/routes/index.js
  server/routes/status.js
Labels: backend

#47 [J054] 동일한 name의 label 검증 버그 수정
  server/models/label.js
  server/services/label.js
Labels: backend, bug

#48 [J182] MilestoneService 구현
  server/models/milestone.js
  server/services/milestone.js
  server/util/date.js
Labels: backend

#50 [J003] label router 추가
  server/routes/api/label.js
  server/routes/index.js
Labels: backend

#54 [J182] Comment Router 구현
  server/routes/api/comment.js
  server/routes/index.js
Labels: backend

#55 [J054] Milestone Router 구현
  server/routes/api/milestone.js
  server/routes/index.js
  server/services/milestone.js
Labels: backend

#56 [J003] label router 응답 코드 수정
  server/routes/api/label.js
Labels: backend, bug

#57 [J182] IssueModel filter구현
  server/models/issue.js
Labels: backend

#58 [J179] issue service 추가
  server/db/models/issue.js
  server/models/issue.js
  server/services/issue.js
Labels: backend

#59 [J179] issue service 의 milestone, comment 상세 정보 추가
  server/db/models/comment.js
  server/models/comment.js
  server/models/issue.js
  server/models/milestone.js
  server/services/issue.js
Labels: backend

#60 [J182] IssueRouter 구현, IssueService 리팩토링, IssueModel 버그 픽스
  server/models/issue.js
  server/routes/api/issue.js
  server/routes/index.js
  server/services/issue.js
Labels: backend

#63 [J179] milestone bug fix by J003
  server/models/milestone.js
  server/services/milestone.js
Labels: backend

#65 [J054] Issue Router 응답 버그 수정
  server/routes/api/issue.js
Labels: backend, bug

#68 assignee 필터 버그 수정
  server/models/issue.js
Labels: backend, bug

#86 [J179] frontend 개발 설정, 폴더 구조 설정
  client/.babelrc
  client/.eslintrc.js
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/api/.gitkeep
  client/src/components/.gitkeep
  client/src/index.js
  client/src/pages/IssueDetail/.gitkeep
  client/src/pages/IssueEditor/.gitkeep
  client/src/pages/IssueList/.gitkeep
  client/src/pages/LabelList/.gitkeep
  client/src/pages/Login/.gitkeep
  client/src/pages/MilestoneEditor/.gitkeep
  client/src/pages/MilestoneList/.gitkeep
  client/webpack.config.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: environment, frontend

#62 [J003] image를 object storage에 올릴 수 있도록 api 추가
  server/package-lock.json
  server/package.json
  server/routes/api/image.js
  server/routes/index.js
  server/routes/middlewares/upload.js
Labels: backend

#88 react eslint 설정 관련된 모듈 설치
  client/package-lock.json
  client/package.json
Labels: environment, frontend

#89 CSS 관련 기본 설정 추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/index.js
  client/src/style/normalize.css
Labels: environment, frontend

#90 [J179] Issue detail & comment 화면 구현
  client/package-lock.json
  client/package.json
  client/public/wheelIcon.svg
  client/src/App.js
  client/src/components/AssigneeContent.jsx
  client/src/components/AssigneeInDetail.jsx
  client/src/components/CommonSidePart.jsx
  client/src/components/DescriptionBody.jsx
  client/src/components/DescriptionHeader.jsx
  client/src/components/DropDown.jsx
  client/src/components/Header.jsx
  client/src/components/LabelContent.jsx
  client/src/components/LabelInDetail.jsx
  client/src/components/MilestoneContent.jsx
  client/src/components/MilestoneInDetail.jsx
  client/src/components/UserProfileUrl.jsx
  client/src/pages/IssueDetail/IssueDetailItem.jsx
  client/src/pages/IssueDetail/IssueDetailPart.jsx
  client/src/pages/IssueDetail/SideAssigneePart.jsx
  client/src/pages/IssueDetail/SideLabelPart.jsx
  client/src/pages/IssueDetail/SideMilestonePart.jsx
  client/src/pages/IssueDetail/index.js
  client/webpack.config.js
Labels: frontend, 우선 순위1 :fire:

#92 [J182] New Issue 정적 View
  client/src/components/.gitkeep
  client/src/components/CharacterCounter.jsx
  client/src/components/DescriptionEditor.jsx
  client/src/components/EditorButton.jsx
  client/src/components/EditorButtonWrapper.jsx
  client/src/components/EditorNavbar.jsx
  client/src/components/EditorWrapper.jsx
  client/src/components/ImageAttacher.jsx
  client/src/components/Textarea.jsx
  client/src/components/TitleEditor.jsx
  client/src/pages/IssueEditor/.gitkeep
  client/src/pages/IssueEditor/IssueEditor.jsx
Labels: frontend

#91 [J054] IssueList 상단 부분 정적인 View 완성
  client/package-lock.json
  client/package.json
  client/src/components/Button.jsx
  client/src/components/DefaultButton.js
  client/src/components/DropdownCaret.js
  client/src/components/DropdownMenu.jsx
  client/src/components/DropdownOverlay.js
  client/src/components/Filter.jsx
  client/src/components/FilterDropdown.jsx
  client/src/components/FilterList.jsx
  client/src/components/GreenButton.jsx
  client/src/components/IssueListHeader.jsx
  client/src/components/IssueListNav.jsx
  client/src/components/LabelButton.jsx
  client/src/components/MilestoneButton.jsx
  client/src/components/SearchBar.jsx
  client/src/pages/IssueList/.gitkeep
  client/src/pages/IssueList/index.js
Labels: frontend

#93 [J003] 리스트로 만들어주는 List.jsx 추가
  client/src/components/IssueListHeader.jsx
  client/src/components/List.jsx
  client/src/components/MilestoneContent.jsx
Labels: frontend, 우선 순위1 :fire:

#94 [J054] Routing 관련 기본 설정 추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header.jsx
  client/src/index.js
  client/src/pages/IssueDetail/index.js
  client/src/pages/IssueList/index.js
  client/webpack.config.js
Labels: frontend

#95 [J182] Issue & Comment Image Attach 기능
  client/package-lock.json
  client/package.json
  client/src/components/CharacterCounter.jsx
  client/src/components/DescriptionEditor.jsx
  client/src/components/EditorWrapper.jsx
  client/src/components/ImageAttacher.jsx
  client/src/components/Textarea.jsx
Labels: frontend, 우선 순위2

#96 [J182] Issue & Comment 작성중 필요 기능
  client/src/components/EditorButton.jsx
  client/src/components/EditorButtonWrapper.jsx
  client/src/components/EditorWrapper.jsx
  client/src/components/TitleEditor.jsx
Labels: frontend, 우선 순위1 :fire:

#97 [J003] babel-polyfill 설치
  client/package-lock.json
  client/package.json
Labels: environment

#98 [J179] Issue Detail 헤더 추가, css 수정, edit 영역 합침
  client/src/components/AssigneeInDetail.jsx
  client/src/components/DescriptionBody.jsx
  client/src/components/DescriptionEditor.jsx
  client/src/components/DescriptionHeader.jsx
  client/src/components/EditorButtonWrapper.jsx
  client/src/components/EditorNavbar.jsx
  client/src/components/EditorWrapper.jsx
  client/src/components/Header.jsx
  client/src/components/IssueDetailHeader.jsx
  client/src/components/MilestoneContent.jsx
  client/src/components/MilestoneInDetail.jsx
  client/src/components/Textarea.jsx
  client/src/pages/IssueDetail/IssueDetailItem.jsx
  client/src/pages/IssueDetail/IssueDetailPart.jsx
  client/src/pages/IssueDetail/SideAssigneePart.jsx
  client/src/pages/IssueDetail/SideLabelPart.jsx
  client/src/pages/IssueDetail/SideMilestonePart.jsx
  client/src/pages/IssueDetail/index.js
  client/src/pages/IssueEditor/IssueEditor.jsx
Labels: frontend, 우선 순위1 :fire:

#99 [J054] IssueListNav에서 동작하는 이벤트 추가
  client/src/components/Button.jsx
  client/src/components/DropdownMenu.jsx
  client/src/components/Filter.jsx
  client/src/components/FilterDropdown.jsx
  client/src/components/FilterList.jsx
  client/src/components/GreenButton.jsx
  client/src/components/IssueListNav.jsx
  client/src/components/LabelButton.jsx
  client/src/components/MilestoneButton.jsx
  client/src/components/SearchBar.jsx
  client/src/pages/IssueList/index.js
Labels: frontend, 우선 순위1 :fire:

#103 [J182] New Issue page, cancel post 버튼 구현
  client/src/App.js
  client/src/components/DescriptionEditor.jsx
  client/src/components/EditorButtonWrapper.jsx
  client/src/components/EditorWrapper.jsx
  client/src/components/ImageAttacher.jsx
  client/src/components/MilestoneContent.jsx
  client/src/components/Textarea.jsx
  client/src/components/TitleEditor.jsx
  client/src/pages/IssueDetail/SideAssigneePart.jsx
  client/src/pages/IssueDetail/SideLabelPart.jsx
  client/src/pages/IssueDetail/SideMilestonePart.jsx
  client/src/pages/IssueEditor/NewIssue.jsx
Labels: frontend

#108 [J003] IssuerList page 추가
  client/src/components/IssueListNav.jsx
  client/src/components/List.jsx
  client/src/components/issueList/IssueContent.jsx
  client/src/components/issueList/Svg.jsx
  client/src/pages/IssueList/index.js
Labels: frontend

#111 [J003] issue state가 정상적으로 표현되지 않던 것을 수정, issue state에 색 추가
  client/src/components/issueList/IssueContent.jsx
  client/src/components/issueList/Svg.jsx
Labels: bug, frontend

#112 [J003] image 전송 요청을 localhost로 보내던 것을 클라우드 서버로 변경
  client/src/components/EditorWrapper.jsx
  client/src/components/ImageAttacher.jsx
  client/src/pages/IssueEditor/NewIssue.jsx
Labels: bug, frontend
